//
//  DeveloperPreview.swift
//  AirBnbClone
//
//  Created by Srimathi  Vadivel  on 6/4/24.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "mpp1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 560,
            latitude: 25.3920,
            longitude: -80.2920,
            imageURLs: ["house1", "house2", "house3", "house4"],
            address: "125 Main Street",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Emily Johnson",
            ownerImageUrl: "fpp1",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 5,
            pricePerNight: 350,
            latitude: 34.0522,
            longitude: -118.2437,
            imageURLs: ["house5", "house6", "house7", "house8"],
            address: "456 Oak Street",
            city: "Los Angeles",
            state: "California",
            title: "LA Townhouse",
            rating: 4.72,
            features: [.superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv],
            type: .townHouse
            ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Michael Brown",
            ownerImageUrl: "mpp2",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 3,
            pricePerNight: 180,
            latitude: 40.7128,
            longitude: -74.0059,
            imageURLs: ["apt1", "apt2"],
            address: "789 Park Avenue",
            city: "New York",
            state: "New York",
            title: "NYC Apartment",
            rating: 4.35,
            features: [.selfCheckIn],
            amenities: [.wifi, .tv],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sarah Wilson",
            ownerImageUrl: "fpp2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 6,
            pricePerNight: 750,
            latitude: 33.7490,
            longitude: -84.3880,
            imageURLs: ["house4", "house5", "house6", "house2", "house13"],
            address: "123 Peachtree Road",
            city: "Atlanta",
            state: "Georgia",
            title: "Atlanta Mansion",
            rating: 3.92,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .pool, .balcony],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "David Thompson",
            ownerImageUrl: "mpp3",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 280,
            latitude: 41.8781,
            longitude: -87.6298,
            imageURLs: ["condo1", "condo2", "condo3"],
            address: "456 Michigan Avenue",
            city: "Chicago",
            state: "Illinois",
            title: "Chicago Condo",
            rating: 2.68,
            features: [.superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jessica Taylor",
            ownerImageUrl: "fpp4",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 450,
            latitude: 29.7604,
            longitude: -95.3698,
            imageURLs: ["house9", "house10", "house11", "house12"],
            address: "789 Main Street",
            city: "Houston",
            state: "Texas",
            title: "Houston House",
            rating: 4.82,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .pool, .office],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Robert Anderson",
            ownerImageUrl: "mpp5",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 3,
            pricePerNight: 220,
            latitude: 38.9072,
            longitude: -77.0369,
            imageURLs: ["apt3", "apt4", "apt5"],
            address: "456 K Street NW",
            city: "Washington D.C.",
            state: "District of Columbia",
            title: "DC Apartment",
            rating: 3.65,
            features: [.selfCheckIn],
            amenities: [.wifi, .tv, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Amanda Garcia",
            ownerImageUrl: "fpp5",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 320,
            latitude: 25.7617,
            longitude: -80.1918,
            imageURLs: ["condo4", "condo5", "condo6", "condo7"],
            address: "789 Ocean Drive",
            city: "Miami Beach",
            state: "Florida",
            title: "Miami Beach Condo",
            rating: 4.78,
            features: [.superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Christopher Davis",
            ownerImageUrl: "mpp6",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 600,
            latitude: 36.1699,
            longitude: -115.1398,
            imageURLs: ["villa1", "villa2", "villa3", "villa4", "villa5"],
            address: "123 Paradise Road",
            city: "Las Vegas",
            state: "Nevada",
            title: "Las Vegas Villa",
            rating: 4.89,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .pool, .balcony, .alarmSystem],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Olivia Martinez",
            ownerImageUrl: "fpp6",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 380,
            latitude: 47.6062,
            longitude: -122.3321,
            imageURLs: ["house13", "house14", "house15"],
            address: "456 Pine Street",
            city: "Seattle",
            state: "Washington",
            title: "Seattle House",
            rating: 4.75,
            features: [.superHost],
            amenities: [.wifi, .kitchen, .laundry, .tv, .balcony],
            type: .house
        ),
    ]
}
